name: azahar-build

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # ============ Windows MSVC ============
  windows-msvc:
    runs-on: windows-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: windows
      TARGET: msvc
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-msvc-${{ github.sha }}
          restore-keys: ${{ runner.os }}-msvc-
      - uses: azahar-emu/msvc-dev-cmd@v1
      - name: Install tools
        run: choco install ccache ninja ptime wget
      - name: Install vulkan-sdk
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.4.304.1/windows/VulkanSDK-1.4.304.1-Installer.exe -O D:/a/_temp/vulkan.exe
          D:/a/_temp/vulkan.exe --accept-licenses --default-answer --confirm-command install
      - name: Disable line ending translation
        run: git config --global core.autocrlf input
      - name: Build
        run: ./.ci/windows.sh
      - name: Pack
        run: ./.ci/pack.sh
      - uses: actions/upload-artifact@v7
        with:
          name: windows-msvc
          path: artifacts/

  # ============ Windows MSYS2 Clang ============
  windows-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: windows
      TARGET: msys2
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-msys2-${{ github.sha }}
          restore-keys: ${{ runner.os }}-msys2-
      - uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: git make p7zip
          pacboy: >-
            toolchain:p ccache:p cmake:p ninja:p spirv-tools:p
            qt6-base:p qt6-multimedia:p qt6-multimedia-wmf:p qt6-tools:p qt6-translations:p
      - name: Disable line ending translation
        run: git config --global core.autocrlf input
      - name: Build
        run: ./.ci/windows.sh
      - name: Pack
        run: ./.ci/pack.sh
      - uses: actions/upload-artifact@v7
        with:
          name: windows-msys2
          path: artifacts/

  # ============ Windows MXE (cross-compile) ============
  windows-mxe:
    runs-on: ubuntu-latest
    container:
      image: opensauce04/azahar-build-environment:latest
      options: -u 1001
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: windows
      TARGET: mxe
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-mxe-${{ github.sha }}
          restore-keys: ${{ runner.os }}-mxe-
      - name: Build
        run: ./.ci/mxe.sh
      - name: Pack
        run: ./.ci/pack.sh
      - uses: actions/upload-artifact@v7
        with:
          name: windows-mxe
          path: artifacts/

  # ============ Linux AppImage ============
  linux-x86_64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["appimage", "appimage-wayland"]
    container:
      image: opensauce04/azahar-build-environment:latest
      options: -u 1001
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: linux
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: ${{ github.job }}-${{ matrix.target }}-
      - name: Build
        run: ./.ci/linux.sh
      - name: Move AppImage
        run: |
          mkdir -p artifacts
          mv build/bundle/*.AppImage artifacts/
      - name: Rename Wayland variant
        if: ${{ matrix.target == 'appimage-wayland' }}
        run: mv artifacts/azahar.AppImage artifacts/azahar-wayland.AppImage
      - uses: actions/upload-artifact@v7
        with:
          name: linux-${{ matrix.target }}
          path: artifacts/

  # ============ macOS Universal ============
  macos:
    runs-on: macos-26
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: macos
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-
      - name: Install tools
        run: brew install ccache ninja spirv-tools
      - name: Build (x86_64)
        run: BUILD_ARCH=x86_64 ./.ci/macos.sh
      - name: Build (arm64)
        run: BUILD_ARCH=arm64 ./.ci/macos.sh
      - name: Create universal app
        run: ./.ci/macos-universal.sh
      - name: Prepare for packing
        run: |
          mkdir build/bundle
          cp -r build/x86_64/bundle build/bundle/x86_64
          cp -r build/arm64/bundle build/bundle/arm64
          cp -r build/universal/bundle build/bundle/universal
      - name: Pack
        env:
          PACK_INDIVIDUALLY: 1
        run: ./.ci/pack.sh
      - uses: actions/upload-artifact@v7
        with:
          name: macos
          path: artifacts/
